version: '3.8'

services:
  sph-assistant-webhook:
    container_name: sph-assistant-webhook
    build:
      context: ./src/Line
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - LineBot__ChannelSecret=${LINE_CHANNEL_SECRET}
      - LineBot__ChannelAccessToken=${LINE_CHANNEL_ACCESS_TOKEN}
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - sph-network

  ngrok:
    container_name: ngrok-tunnel
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http sph-assistant-webhook:8080 --log=stdout
    depends_on:
      - sph-assistant-webhook
    restart: unless-stopped
    networks:
      - sph-network

networks:
  sph-network:
    driver: bridge
